// Copys del panel de administración. La sección `armazon` viene de 04-copys.md
// tal cual. El resto (acceso, listado, formulario, cuenta) se ha redactado ahora
// siguiendo el mismo tono para tener maquetación funcional cuanto antes: falta
// contrastarlo frase a frase contra 04-copys.md antes de darlo por cerrado.
export const copysAdmin = {
  armazon: {
    marcaLinea1: 'Confecciones',
    marcaLinea2: 'Ana Mari',
    marcaSufijo: 'Administración',
    modoAdmin: 'Modo administrador',
    navProductos: 'Productos',
    navUsuarios: 'Usuarios',
    verLaWeb: 'Ver la web ↗',
    nombreUsuaria: 'Ana',
    miCuenta: 'Mi cuenta',
    salir: 'Salir',
  },
  acceso: {
    titulo: 'Entrar',
    campoEmail: 'Correo',
    campoContrasena: 'Contraseña',
    boton: 'Entrar',
    botonEnviando: 'Entrando…',
    errorGenerico: 'Correo o contraseña incorrectos.',
  },
  listado: {
    titulo: 'Productos',
    buscar: 'Buscar por nombre',
    filtroTodos: 'Todos',
    filtroRopa: 'Ropa',
    filtroMerceria: 'Mercería',
    anadir: 'Añadir producto',
    columnaNombre: 'Nombre',
    columnaCategoria: 'Categoría',
    columnaPrecio: 'Precio',
    columnaEstado: 'Estado',
    estadoVisible: 'Visible',
    estadoOculto: 'Oculto',
    etiquetaAgotado: 'Agotado',
    etiquetaDestacado: 'Destacado',
    vacioTitulo: 'Todavía no hay productos',
    vacioTexto: 'Añade el primero para que aparezca en el catálogo público.',
    cargando: 'Cargando productos…',
    errorCarga: 'No se ha podido cargar el listado.',
  },
  formulario: {
    tituloNuevo: 'Añadir producto',
    tituloEditar: 'Editar producto',
    seccionDatos: 'Datos del producto',
    cancelar: 'Cancelar',
    seccionFotos: 'Fotos',
    fotosArrastra: 'Arrastra las fotos aquí',
    fotosPulsa: 'o pulsa para elegirlas',
    fotosPendiente: 'Todavía no se ha decidido cómo se subirán las fotos. Esto es solo maquetación.',
    campoNombre: 'Nombre del producto',
    nombrePlaceholder: 'Escribe el nombre',
    nombreAyuda: 'Corto y claro. Ej.: «Bata azul con bolsillos».',
    campoDescripcion: 'Descripción',
    descripcionPlaceholder: 'Escribe la descripción',
    descripcionAyuda: 'Tres o cuatro líneas: tejido, corte y para qué sirve.',
    campoPrecio: 'Precio (€)',
    campoComposicion: 'Composición',
    campoColores: 'Colores',
    campoCaracteristica: 'Característica destacada',
    seccionCatalogo: 'Catálogo',
    tipoRopa: 'Ropa',
    tipoMerceria: 'Mercería y costura',
    seccionCategoria: 'Categoría',
    seccionTallas: 'Tallas disponibles',
    seccionTipoMerceria: 'Tipo de artículo',
    seccionAtributos: 'Colores del producto',
    campoVisible: 'Publicado',
    campoVisibleAyuda: 'Se ve en la web',
    campoAgotado: 'Agotado',
    campoAgotadoAyuda: 'Aparece marcado como sin existencias',
    campoDestacado: 'Destacado',
    campoDestacadoAyuda: 'Aparece en la portada',
    guardar: 'Guardar',
    guardando: 'Guardando…',
    borrar: 'Borrar producto',
    borrando: 'Borrando…',
    confirmarBorrarTitulo: '¿Borrar este producto?',
    confirmarBorrarTexto: 'Desaparece de la web y no se puede recuperar.',
    confirmarBorrarBoton: 'Sí, borrar',
    notaSinBorrar: 'Al crear no hay «Borrar»: no hay nada que borrar todavía.',
    errorGenerico: 'Revisa los datos del producto.',
    creadoOk: 'Producto creado.',
    guardadoOk: 'Cambios guardados.',
  },
  cuenta: {
    titulo: 'Mi cuenta',
    seccionContrasena: 'Cambiar contraseña',
    campoActual: 'Contraseña actual',
    campoNueva: 'Contraseña nueva',
    ayudaMinimo: 'Al menos 8 caracteres.',
    boton: 'Guardar contraseña',
    botonEnviando: 'Guardando…',
    exito: 'Contraseña actualizada.',
    errorActual: 'La contraseña actual no es correcta.',
    salir: 'Salir de la sesión',
  },
  confirmarSalir: {
    titulo: '¿Salir de la sesión?',
    texto: 'Tendrás que volver a entrar con tu correo y contraseña.',
    boton: 'Sí, salir',
  },
  usuarios: {
    titulo: 'Usuarios',
    anadir: 'Añadir usuario',
    columnaNombre: 'Nombre',
    columnaCorreo: 'Correo',
    columnaRol: 'Rol',
    columnaEstado: 'Estado',
    estadoActivo: 'Activo',
    estadoInactivo: 'Inactivo',
    rolAdminWeb: 'Administrador',
    rolPropietario: 'Propietaria',
    rolCliente: 'Cliente',
    vacioTitulo: 'Todavía no hay usuarios',
    vacioTexto: 'Añade el primero para dar acceso al panel.',
    cargando: 'Cargando usuarios…',
    errorCarga: 'No se ha podido cargar el listado.',
  },
  formularioUsuario: {
    tituloNuevo: 'Añadir usuario',
    tituloEditar: 'Editar usuario',
    campoNombre: 'Nombre',
    campoCorreo: 'Correo',
    campoRol: 'Rol',
    campoContrasena: 'Contraseña',
    campoContrasenaNueva: 'Contraseña nueva (opcional)',
    ayudaContrasenaNueva: 'Déjalo en blanco para no cambiarla.',
    ayudaMinimo: 'Al menos 8 caracteres.',
    campoActivo: 'Activo',
    campoActivoAyuda: 'Puede entrar al panel',
    guardar: 'Guardar',
    guardando: 'Guardando…',
    borrar: 'Borrar usuario',
    borrando: 'Borrando…',
    confirmarBorrarTitulo: '¿Borrar este usuario?',
    confirmarBorrarTexto: 'Perderá el acceso al panel y no se puede deshacer.',
    confirmarBorrarBoton: 'Sí, borrar',
    errorGenerico: 'Revisa los datos del usuario.',
    errorCorreoDuplicado: 'Ya existe un usuario con ese correo.',
    errorPropioAcceso: 'No puedes quitarte tu propio acceso.',
  },
} as const;
